### ISSUE TITLE
Doesn't load on Windows Phone

### ISSUE THREAD

**Issue by R2D221** [hivewallet/hive-js#120]
I just wanted to try the new Hive webapp, but it just shows a splashscreen and then nothing happens. I'm using a Nokia Lumia 520 with Windows Phone 8 update 3.

![Splashscreen on Nokia Lumia 520, Windows Phone](https://vmvhfa.bn1.livefilestore.com/y2mM4XANTGfb7KSIbvNZMTihf7BgLMmDaCoZHpTWKae6Cg1x5VMLFegUMlqHE5gI27DOrAOSIWwTBjADlwBebERbALkOIb0QG_4yiGF4M_uxfJEBcgB1seSriVXw74BKw6A/wp_ss_20140624_0001.png?psid=1)

**Comment by w-hive** [comment]
Current version of Hive probably won't support any more devices, but we can re-examine this situation for Hive 2.0.
