### ISSUE TITLE
Remove ability to copy seed / Add seed check screen.

### ISSUE THREAD

**Issue by dabura667** [hivewallet/hive-js#138]
I think it is important to write down the seed, but some people may forget to write it down, and later want to export it to another device / make a backup of their hive wallet after creation.

What are your thoughts on this functionality?

Maybe call it "Show backup phrase", then show a warning message that says anyone who knows this phrase can use your bitcoins, then require PIN.

These features I am suggesting are geared more towards the "I want to verify what my app is telling me independently" type people. This might not be the audience, but these features should have some sort of non-intuitive way to enable them. (hidden advanced mode or long presses that are longer than most people would ever think to hold a button, etc.)

**Comment by w-hive** [comment]
UX issue to be solved in Hive 2.0.
