### ISSUE TITLE
Japanese language specific issues

### ISSUE THREAD

**Issue by mattatgit** [hivewallet/hive-js#192]
* minor layout breaking issues.

![default](https://cloud.githubusercontent.com/assets/6858525/3872553/87a61182-211e-11e4-9316-14d544df646c.PNG)

![default](https://cloud.githubusercontent.com/assets/6858525/3872544/3cfaab3e-211e-11e4-87eb-702aa76b1eb9.PNG)

![jp3](https://cloud.githubusercontent.com/assets/6858525/3872565/b268d864-211e-11e4-8abd-7d33b44a47c4.png)

**Comment by w-hive** [comment]
Closing. UX issue to be solved with Hive 2.0.
