### ISSUE TITLE
Support form: option to attach receive account and change account's extended public keys

### ISSUE THREAD

**Issue by weilu** [hivewallet/hive-js#202]
Useful information for debugging some support cases. Currently there's no way on the UI for users to export such information. I'm thinking about adding a custom field to zendesk and expose the option to "attach receive account and change account's extended public keys" as a checkbox in the support form. Thoughts @jenbennings @haustraliaer?

**Comment by w-hive** [comment]
Closing for now, since we won't be addressing this for some time (if at all).
