### ISSUE TITLE
History: display change address incoming transactions

### ISSUE THREAD

**Issue by weilu** [hivewallet/hive-js#204]
Currently we do not display incoming transactions going into change addresses because we consider change addresses internal addresses -- addresses that we never expect users to hand out for receiving funds. But it's not the case in Satoshi Dice, return bets are sent back to the address where the funds come from -- there could be cases where funds came from change addresses, users will not be able to see the return bets in history.

**Comment by w-hive** [comment]
Closing due to this probably not changing for this version of Hive.

**Comment by weilu** [comment]
This has been resolved since we moved to using cb-wallet
