### ISSUE TITLE
Warning on 5th input of pin

### ISSUE THREAD

**Issue by KBenavidez** [hivewallet/hive-js#207]
Right now, the users will just continue to try to enter the wallet and forget how many times they were able to input their pin. It would be nice if the user can see a warning saying : "This is the 5th time you will be trying to open your wallet. If your PIN input is still incorrect, you will need to use your passphrase after this."

**Comment by w-hive** [comment]
Closing and setting the UX portion of this to be Matt's issue for Hive 2.0

**Comment by mattatgit** [comment]
@w yep, if we're going to allow the seed phrase to be shown in settings as previously discussed, we're going to require a solution for resetting forgotten PINs (ie email address etc)
