### ISSUE TITLE
Hint for wallet address

### ISSUE THREAD

**Issue by mattatgit** [hivewallet/hive-js#209]
Based on the "what is this address stuff?" questions we're getting via support, it seems like the goal of getting Bitcoin beginners on Hive is working. So maybe what we need is a modal tip along same lines as we have for Waggle & Gravatar, for the wallet address.

I'd suggest something like "Enter the wallet address you'd like to send coins to. You can get the address from Waggle if the receiver is nearby and uses Hive. The wallet address will look something like this: 1qs4xQpt8nMz1po9t5ave"

**Comment by w-hive** [comment]
@mattatgit Let's incorporate this into the new design. Closing this issue for now.
