### ISSUE TITLE
Make support mail more explicit for users

### ISSUE THREAD

**Issue by KBenavidez** [hivewallet/hive-js#211]
With the incoming support tickets, I have noticed that many have mistaken the support button as a profile status in a way. I don't actually know how these people can actually mistaken given it's written as "support" though. Perhaps we can put "Please specify your problem" than "description" ?

**Comment by w-hive** [comment]
Issue to be solved in Hive 2.0. Closing for now.

**Comment by mattatgit** [comment]
yeah we haven't designed exactly how this will work yet. Current thought is the support will be via a Hive support app in the app section (with links to it from other parts of the UI). We'll look at this soon, and ensure it is worded better to avoid the problems above.
