### ISSUE TITLE
web.hivewallet.com not working for safari 8

### ISSUE THREAD

**Issue by toomasj** [hivewallet/hive-js#216]
https://web.hivewallet.com not working under MacOSX Yosemite and Safari 8.0.
When opening page, is see the small "lock" load and finally the key turns, but the "login screen" does not appear.

In Developer Tools Console i have following messages:
[Error] Viewport argument key "minimal-ui" not recognized and ignored. (web.hivewallet.com, line 7)
[Error] NotFoundError: DOM IDBDatabase Exception 8: An operation failed because the requested database object could not be found.
	transaction (application-en.js, line 635)
	onsuccess (application-en.js, line 635)

**Comment by w-hive** [comment]
Related to #234 ? Closing.
