### ISSUE TITLE
Doesn't recognize pin

### ISSUE THREAD

**Issue by hillarysousa** [hivewallet/hive-js#227]
even though I wrote the correct pin, it shows that the pin is wrong. I tried to type it wrong 5 times, so I could change it, but when I'm prompted to change the pin, it shows the pin is wrong.

**Comment by hillaryhp** [comment]
So, is Hivewallet wroking again? tried to login but the issue is still there.

**Comment by weilu** [comment]
Staging or production? Screenshot and error log?

**Comment by hillaryhp** [comment]
For me it's still the same error as before. When I try to access it tells
me the PIN is wrong, when I try to set a new pin it tells me the pin is
wrong. I tried to acess the other link, hive-js.herokuapp.com, but it
returned me the following error:

[image: Imagem inline 1]

--
*Hillary Sousa*
*Web & Graphic Designer*

2015-01-09 3:48 GMT-02:00 Wei Lu <notifications@github.com>:

**Comment by hillaryhp** [comment]
![image](https://cloud.githubusercontent.com/assets/10313411/5675959/d64bfd46-97b2-11e4-9aaf-f560a9bc0670.png)

**Comment by weilu** [comment]
Looks like a timeout issue. Can you bring up the console and tell me what the error is on the console? Do you have a lot of transactions in your wallet?

**Comment by hillaryhp** [comment]
I have 12 transactions, I think. Here's the console error:

 Velocity is already loaded or its namespace is occupied.
blob:https%3A//hive-js.herokuapp.com/956477b7-b8fe-4552-bc9a-f999d42ebd18 Failed to load resource: the server responded with a status of 404 (Not Found)
application-en.js:3627 The above 404 is totally normal. PouchDB is just detecting blob URL support.
application-en.js:3149 Discovered 1 addresses
hive.cloudant.com/?_nonce=zxYGtCPd6dmEHQkL:1 GET https://hive.cloudant.com/?_nonce=zxYGtCPd6dmEHQkL 403 (Forbidden)
application-en.js:3149 Discovered 0 addresses
hive.cloudant.com/?_nonce=nYRly0yt0d9fXkAK:1 GET https://hive.cloudant.com/?_nonce=nYRly0yt0d9fXkAK 403 (Forbidden)
hive.cloudant.com/?_nonce=A3GIPu0kNsh97NSv:1 GET https://hive.cloudant.com/?_nonce=A3GIPu0kNsh97NSv 403 (Forbidden)
application-en.js:3294 Error: Internal XMLHttpRequest Error {statusCode: 0, stack: (...), message: "Internal XMLHttpRequest Error"}message: "Internal XMLHttpRequest Error"stack: (...)get stack: function () { [native code] }set stack: function () { [native code] }statusCode: 0__proto__: dapplication-en.js:3294 eapplication-en.js:3549 (anonymous function)application-en.js:3146 (anonymous function)application-en.js:3149 (anonymous function)application-en.js:3188 (anonymous function)application-en.js:3190 (anonymous function)application-en.js:5 (anonymous function)application-en.js:5 uapplication-en.js:5 (anonymous function)application-en.js:5 (anonymous function)application-en.js:5 (anonymous function)application-en.js:3190 (anonymous function)application-en.js:3160 (anonymous function)application-en.js:3178 (anonymous function)application-en.js:3172 oapplication-en.js:3172 n

**Comment by Paol33** [comment]
Hi, I have been suggested (by assistance) to post here my problem as I try to open my BTC wallet on HIVE : I have no problems to enter LTC wallet, but as I digit the 4 Numbers code in the BTC wallet the system asks againg for the code, despite showing dots in the boxes; change of code did not help; I tried to access with LINUX UBUNTU (Mozilla and Chrome) and also with Microsoft XP (Outlook) , but I still cant access my wallet...
