### ISSUE TITLE
Balance display is off

### ISSUE THREAD

**Issue by w-hive** [hivewallet/hive-js#228]
Quote from a user email:

Once I'm in the wallet, it shows the wrong balance. Right now it shows 0 BTC. But on the history tab, I can see all of my transactions. They are (most recent first):
-0.52278527 + -0.00304 + 0.00416 + -0.00304 + 0.00294 + -0.00312 + 0.00333 + -0.00100 + 0.00100 + 0.08566 + 0.06395 + 0.01407 + 0.07582 + 0.08852 + 0.08634 + 0.08836 + -0.00980 + -0.00780 + 0.03710 + -0.00990 + 0.00950 + -0.01000 + -0.01000 + 0.00100 + -0.01000 + -0.02150 + 0.04940 + 0.00200
If you add all that up, you get 0.00116473, but my balance is reported as 0.

When attempting to login, I see a couple of external resources that fail for various reasons:
403's like: https://hivewallet.cloudant.com/?_nonce=Rmq6llaua8D5gdPX
404's like: https://hivewallet.cloudant.com/hivec09ad2cb2ef31181f29c1eedc6df0c42f8592bdcf36aa9419ee58460cd438822/_local/s0jDOigwdKwGaFbdvyOgzw==?_nonce=f95OTiwypwxSV8In

**Comment by jacob101fishy** [comment]
I'm having the same problem as undefx, my account should be at around ~0.3 btc, I tried logging into https://web.hivewallet.com/ but it says my pin is invalid for that wallet, and my wallet is only accessible through https://hive-js.herokuapp.com/

http://imgur.com/t5Nvt2Q

**Comment by w-hive** [comment]
@jacob101fishy Thanks for the report. We'll get the stuff on Heroku deployed to web.hivewallet.com soon.

**Comment by weilu** [comment]
@jacob101fishy use https://web.hivewallet.com/ and try with the same pin 5 times, it will ask you to enter your 12-word passphrase and reset your pin. Then you can move your funds.

**Comment by jacob101fishy** [comment]
@weilu tried entering my pin more than five times and nothing happened just kept telling me my pin was incorrect

**Comment by jacob101fishy** [comment]
@weilu Got it to work I had to reopen my browser in incognito mode but it finally let me change my pin and my btc balance is what it should be

**Comment by weilu** [comment]
Instead of incognito, you can also try clearing the browser cache & cookies for hivewallet.com. Regardless, I'm in the process of deploying a fix to our staging site https://hive-js.herokuapp.com/. @jacob101fishy if you haven't moved your funds, let me know if your balance issue is fixed on staging.

**Comment by jacob101fishy** [comment]
@weilu Yes Ive moved my funds and everything is good to go, thanks for the help it was much appreciated(:
