### ISSUE TITLE
I still can't access my web wallet

### ISSUE THREAD

**Issue by pennyfx** [hivewallet/hive-js#229]
I created a web wallet in August 2014.  I haven't been able to access it for months.   When I restore it and then type in the pin, Hivejs just spins.    What is going on?

So I was able to recover it using incognito mode.  So it must be an issue with something that is stored in localstorage or indexdb.

**Comment by weilu** [comment]
Try our staging site with your 12-word passphrase. If it still doesn't work for you can you take a screenshot of the error and if you know how get the console output and post them here

**Comment by pennyfx** [comment]
It doesn't have an error.  It just freezes after I enter my pin code.   My wallet works on the staging site, but I think it is because I just restored it from the passphrase and it is *new*.

**Comment by enricribas** [comment]
I agree. This is happening for me as well. It accepts my pin and then spins and spins forever. I click on open existing wallet, enter the passphrases, then enter a new PIN, and then the same thing. 

I am using the Android version. 

Obviously very frustrated

**Comment by w-hive** [comment]
Possibly related to:

https://github.com/hivewallet/hive-js/issues/233#issuecomment-113821036

**Comment by w-hive** [comment]
Please try http://hive-js.herokuapp.com with your passphrase and let us know if it works.

**Comment by w-hive** [comment]
Closing this and other redundant issues now; #237 and #239 exist to consolidate. You guys may continue to comment here however.
