### ISSUE TITLE
network connection error on hive

### ISSUE THREAD

**Issue by randlev2** [hivewallet/hive-js#230]
hi. i recently sent bitcoin to my wallet. upon opening my wallet to check if the funds had been received i got an error msg displaying across the top of the wallet saying 'network connection error'. ive restarted the wallet and each time this error shows. the funds are still not showing and the confirmations are up to 4 but going very slowly. any help much appre

**Comment by skyjam** [comment]
When sending a outbound transaction I get an error saying I'm not online. This only happens in Safari on Mac. Chrome on the same Mac does not give this error. Same from Safari on iPad.

**Comment by w-hive** [comment]
Possibly related to:

https://github.com/hivewallet/hive-js/issues/233#issuecomment-113821036

**Comment by w-hive** [comment]
Please try http://hive-js.herokuapp.com with your passphrase and let us know if it works.

**Comment by w-hive** [comment]
Closing this and other redundant issues now; #237 and #239 exist to consolidate. You guys may continue to comment here however.
