### ISSUE TITLE
i cant open my wallet!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by asoroka27** [hivewallet/hive-js#243]
previously all worked well! Now when I open my wallet, the synchronization is long and does not open the wallet! what to do?

**Comment by asoroka27** [comment]
fucking hivewallet! where is my money?????? you

**Comment by asoroka27** [comment]
http://hive-js.herokuapp.com/
i can open but cant send money (bitcoin) and not see transaction

**Comment by weilu** [comment]
FOR NOW ON THE STAGING VERSION YOU NEED TO WAIT FOR TRANSACTIONS TO FINISH LOADING BEFORE YOU CAN SEND. MIND YOUR MANNERS.

**Comment by asoroka27** [comment]
when will be work my wallet?
