### ISSUE TITLE
ASAP!!!!

### ISSUE THREAD

**Issue by asoroka27** [hivewallet/hive-js#245]
when I open my wallet, the synchronization is long and does not open the wallet
alredy 24 hours

**Comment by asoroka27** [comment]
![bad](https://cloud.githubusercontent.com/assets/14103041/9660380/06a97fca-525e-11e5-9cd9-54b1afb4ca46.jpg)

screen! synchronization and not open wallet!

**Comment by asoroka27** [comment]
allo

**Comment by mackuba** [comment]
FYI, I worked on the Mac app, but I have nothing to do with the iOS/web app. Please don't stalk me on GitHub and spam unrelated projects' issues... ಠ_ಠ

**Comment by aeonixsi** [comment]
Having the same problem. Animation loads, then a blank screen. I've tried from several browsers on several machines. I have a significant amount of money locked up in this wallet and I cannot access it. Is this issue being looked into????

**Comment by ghost** [comment]
Try using this one with your passphrase:

http://hive-js.herokuapp.com

If the issue persists, clear your cache and try that above again.

**Comment by aeonixsi** [comment]
Same issue with the link above. I have cleared my cache, used different browsers, different machines, different ISPs, same issue persists. The animation loads, then nothing. Blank page. Not even a prompt for my wallet passphrase. This issue is absolutely NOT closed. This needs resolution.

**Comment by ghost** [comment]
I'm not really sure what to tell you, it works on this side.

Try using your passphrase with a different wallet, such as Bread Wallet on iOS. Or any other BIP32/BIP39 wallet.

**Comment by aeonixsi** [comment]
I was hoping you would 'tell me' you are working on resolving this issues. I am clearly not the only one experiencing it. I have tried other browsers, the alternate link, different PCs with different OS's, different ISPs spanning across different states. The same issue persists. I get the animated icon to load, it does its thing and disappears, then nothing. No prompt for login, just a dead purple background.

I don't have an IOS device. Is there ANY other possible way to access a web wallet created on hive???

**Comment by ghost** [comment]
I'm sorry but we can't reproduce it so we can't resolve it either.

You have a BIP32/BIP39 passphrase, which is portable to any other wallet which supports that standard, by design. I believe Mycelium (which is multiplatform) can take it directly, as well as Bread Wallet. And if you can't find one that supports that standard, you can use the tools at bip32.org to sweep your keys into _any_ wallet.

I wish you luck!
