### ISSUE TITLE
Hive wallet frozen on "synchronizing wallet"...

### ISSUE THREAD

**Issue by emiraro** [hivewallet/hive-js#247]
Hi,

While i properly and securely stored my passphrase, and while my pin is correct, i'm still unable to access my wallet.
After the login, it stays frozen in the "synchronizing wallet". I tryed to connect from different device (ios on iphone and ipad, and on the web app from two different web browsert -safari and firefox and chrome). I also tried to clear cookies and cache, and to delete and reinstall the app on iphone before to start again.

Since a few minutes it is now frozen in the verifying pin step.
How can i get access to my wallet back again?

**Comment by ghost** [comment]
Did you try the staging version?

http://hive-js.herokuapp.com/

**Comment by emiraro** [comment]
Yes I tried but it is not working (wrong btc amount, it is negative)

**Comment by ghost** [comment]
I'm not really sure what to tell you in that case. Try putting your passphrase into another BIP32+BIP39 wallet, for example Bread Wallet on iOS. As you may know, Hive is now unsupported software, so you're probably better off doing that anyway. https://twitter.com/hivewallet/status/645402186260721664
