### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by ghost** [hivewallet/hive-js#249]
Followed README.md up to Profit.
`DB_HOST=...` command returned "sh: aperture: command not found", so I `npm install -g aperture`.
Then "Error: Cannot find module 'async'". So I `npm install async`.
Then "Error: Cannot find module 'express'". So I `npm install express`.
It keeps going. I'm now up to "Error: Cannot find module 'cookie-session'".
Sure I'm on the wrong track, don't want to keep going. Please could you help?

**Comment by ghost** [comment]
PS. I'm trying to make my implementation of [gift-spending](https://github.com/willnwhite/gift-spending) work with Hive.

**Comment by weilu** [comment]
Did you do `npm install` after you clone the repo?

**Comment by ghost** [comment]
Sorry, I can't remember. I will log the issue again if I find it's still a problem.
