### ISSUE TITLE
Low-S ECDSA signatures

### ISSUE THREAD

**Issue by losh11** [hivewallet/hive-js#250]
Please implement low-s ECDSA signatures, as when Litecoin Core 0.10.3 is release, no block will accept any transactions signed without.

@w-hive

**Comment by dabura667** [comment]
hive is based off bitcoinjs-lib, which afaik has supported low-s for a loooooooooong time.

Whether it's in the compiled apps on each respective app store, idk.

**Comment by ghost** [comment]
Losh do you need me to take further action on this? It sounds like you'll need to bake in the latest bitcoinjs-lib.

**Comment by dabura667** [comment]
https://github.com/hivewallet/hive-js/blob/6f33f81279ffbab6332dff089a2870de752d5589/package.json#L39

Release 0.3.3 of hive-js has ^1.2.0 for the bitcoinjs-lib dependency.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/cfcfe59520f1c24d6b1174dbf769d778a5484fce/src/ecdsa.js#L71

bitcoinjs-lib @ 1.2.0 supports LowS signatures.

This issue should be closed.
