### ISSUE TITLE
Help test Hive iOS

### ISSUE THREAD

**Issue by losh11** [hivewallet/hive-js#252]
Before I create a pull request, can I have someone test Hive-iOS?
Here's the link: [https://github.com/losh11/hive-ios](https://github.com/losh11/hive-ios)

I've been experiencing some server issues, but if anyone finds that it works for them, please do tell. There are some CSS issues with the iOS specific buttons, which I will try to patch. I'm not too good with couchdb, so if someone could test if the app works with iOS sim (it works perfectly running from localhost) as an app. 

@w-hive If you could do this, that would be great. I want to make the pull request as soon as I can.

**Comment by ghost** [comment]
Hi Losh,

I certainly would do but I have neither an iOS device, nor a system that can build iOS apps. :(

Pinging @weilu who might.

**Comment by losh11** [comment]
Any update?

If the build doesn't work, I would recommend building hive first (with the prod.config filled in) and then copy the contents of the build/\* file into cordova/www/. That should contain all the HTML and other files. After that, cd back into the cordova/ folder, and the run the terminal command `cordova build ios` or `cordova run ios`.

**Comment by weilu** [comment]
@losh11 Your commit https://github.com/losh11/hive-ios/commit/f74953a24e316f0d97ce89d426629207dc2a9804 is impossible to review as it includes both modified files and generated files. Can you separate the changes you made to hive-js and make a PR against this repo please? Hive iOS testing request doesn't belong here anyway.
