### ISSUE TITLE
Public URL for Hive web wallets

### ISSUE THREAD

**Issue by haustraliaer** [hivewallet/hive-js#27]
The following is an outline for the _opt in_ feature of having your chosen username and address details made public at a human readable url, eg: `hivewallet.com/mattinnes`. If anyone has any serious concerns with this now is the time to voice them, otherwise we will proceed with the understanding that the public url/profile system will work in this way.

After the lengthy discussions last night and in an effort to keep things moving, I'm proposing we ditch any ideas of this url being able to generate unique addresses - which seemed fraught with potential abuse of the technical limitations in HD wallets. 

Instead the address will be _static_ and made clear to the user that it is a _public_ address. See the attached diagram for further notes on this proposal:

![hive_public_url_system](https://cloud.githubusercontent.com/assets/1561116/2774117/78247d18-caaf-11e3-958c-effe44f4dc94.png)

### Implications for hive contacts

The second point worth bringing into this discussion is how two hive-js accounts might leverage this system to connect to one another. Obviously I could just send coins to my friend's public address, or ask him for a unique address. However, if we were both using hive we gain the advantage of "pairing" our accounts and creating a unique address for each of our two wallets to send transactions through. The clear advantages being:

a) I don't have to generate a new address for sending coins to this contact
b) The only people who know of the transactions are myself and the contact
c) I would go so far to say that the actual addresses could probably be hidden from even the hive users, to make things simpler on their end.

From a UI perspective, there might be a prompt on the public page - `hivewallet.com/mattinnes` - to simplify this connection (which could send non-hive users to a sign up page). We'll be looking at the issue of connecting contacts in more detail as we go along, but I thought it would be worth mentioning here as the public url system will likely be coupled to the contact system.

**Comment by w-hive** [comment]
Feature discussed for Hive 2.0.
