### ISSUE TITLE
Set preferred bitcoin denomination

### ISSUE THREAD

**Issue by weilu** [hivewallet/hive-js#3]
Support BTC, mBTC, μBTC. Default to mBTC like hive-osx. This should be a persisted, per-user system wide setting.

**Comment by w-hive** [comment]
Closing until Hive 2.0 is ready. An issue for @mattatgit  to analyze and decide.

**Comment by mattatgit** [comment]
@w-hive yeah i think we could add this an an option in the slide out drawer of Hive 2 for the master token (in the case its BTC, you can select your preferred option ie  BTC or bits (which seems to be the current winner in this nomenclature debate). We've got enough space in the UI to fit the (potentially) long numbers required for bits, so should be no problem
