### ISSUE TITLE
Forgot/Reset PIN

### ISSUE THREAD

**Issue by weilu** [hivewallet/hive-js#80]
Currently to reset pin one will need to enter a wrong pin 5 times, then the user will be prompted to enter their passphrase again, followed by setting a new pin. We should make this process easier.

"I forgot my PIN" link/button, which yields an input where I can enter my passphrase, followed by a 'set new PIN' prompt

**Comment by w-hive** [comment]
Closing for the time being. This will be reworked for Hive 2.0.
