### ISSUE TITLE
Interface Copywriting

### ISSUE THREAD

**Issue by jenbennings** [hivewallet/hive-js#82]
I will handle interface copywriting edits in the lead up to the beta release. If you find any grammatical errors, typos, or have any general suggestions—please put them here.

To-do:

- [ ] Replace "Logout" in settings drawer with "Lock wallet"
- [ ] "Set your PIN for this device" (when opening an existing wallet)

**Comment by w-hive** [comment]
@mattatgit I like most of the suggestions here, let's incorporate into Hive 2.0.

**Comment by mattatgit** [comment]
@w yep, already have (copywriting for initial seed phrase handling at least). Re having a message in waggle etc – seems like an edge case, given that for anyone using mobile apps, the QR scan is faster & more secure. Waggle is already kind of a slow process, i don't think slowing it down further is such a great idea.
